print("yan\"ling\njiefa".upper())
print("i am yanling".islower())
print("it's so boring today"[10])
print("it's so boring today".index("r"))
print("it's so boring today".replace("boring","happy"))
print(-2.55)
print((3-5)*6)
print(10%5)
my_num=-5
print(str(my_num) + " my favorite number")
print(abs(my_num))
from math import*
print(abs(-12))
print(pow(3,4))
print(max(6,5,14,-18,2))
print(min(6,5,14,-18,2))
print(round(3.78))
print(ceil(3.78))
print(floor(3.78))
print(sqrt(36))
name=input("enter your name:")
age=input("enter your age:")
print("hello " + name +" ! your are  " + age )
num1=input("Enter your number:")
num2=input("Enter another number:")
result=float(num1)+float(num2)
print(result)
color=input("Enter a color:")
plural_noun=input("Enter a plural noun:")
celebrity=input("Enter a celebrity:")

print(" roses are " +color)
print(plural_noun + " are blue" )
print("i love " + celebrity)
friends=["kevin","karen","jim","tom" ,"lucy"]
print(friends[0])
print(friends[-2])
print(friends[1:])
print(friends[1:3])
friends[1]="mike"
print(friends[1:4])